### ISSUE TITLE
Last version - Development Branch

### ISSUE THREAD

**Issue by kenneth-bolivar-castro** [mrjmd/pdb#78]
I noticed that branch: "**8.x-1.x**" is different than release version at Drupal.org,
https://www.drupal.org/project/pdb/releases/8.x-1.0-alpha1

Since it's "_8.x-1.0-alpha1_" tag  into this repository, I am confused, which branch should we use to develop feature or fix issues?

I created four new PR, based on "*8.x-1.x" branch,
- https://github.com/mrjmd/pdb/pull/71

Is it correct use that branch as development one?

**Comment by mrjmd** [comment]
Yes, I believe this is the typical workflow for Drupal modules.... 8.x-1.x will always be the dev branch (until we cut a 2.x), and releases will be tags made on that branch. Since we're still in alpha there's no need yet to roll hotfix branches off of release tags, so fixes should be made on the 8.x-1.x branch and will get added to the next alpha release.

Thanks for your help!
