### ISSUE TITLE
Components not loading in blocks with Drupal JS aggregation 

### ISSUE THREAD

**Issue by shrop** [mrjmd/pdb#85]
I was not able to get the test Angular 2 components in blocks with Drupal JS aggregation turned on. The block title shows and that is it. Turning off JS aggregation and drush cr allows the components to run properly. 

* Used core theme
* On branch `feature/ng-prime`
* `npm install` was run in `modules/pdb/modules/pdb_ng2`

I think this would probably happen on the 8.x-1.x, but haven't confirmed yet.

**Comment by kenneth-bolivar-castro** [comment]
@shrop it happens because when Drupal executes aggregation some dependencies don't meet, I think, it's something related with order they are loaded, but I haven't work in solve this issue then I am not for sure that's what's happening there, so what I did was disable aggregation for now.

I think, we could fix this issue by any of the following ways:

- [Disable aggregation for Angular 2 libraries](https://www.drupal.org/developing/api/8/assets#disable-aggregation) by adding `{preprocess: false}` to library definition.
- [Load all Angular 2 framework in the header](https://www.drupal.org/theme-guide/8/assets) by adding `header:true` within library defintion.

If you have another idea, feel free to share it,

**Comment by shrop** [comment]
Thank you! Yeah, I am leaving JS aggregation turned off for now.

Will dig more as I can this week. :)

**Comment by mrjmd** [comment]
This should be working now with the changes I made while upgrading to RC3, luckily without moving anything more to the header (but I did move rxjs out of the library). I've tested several example components with aggregation turned on and am not having any issues. Please reopen if that's not the case.
