### ISSUE TITLE
Where to put custom components / upgrading pdb

### ISSUE THREAD

**Issue by acha5066** [mrjmd/pdb#88]
Hi there, sorry if this is a stupid question but I'm not clear on the upgrade path when building custom components. 

What I have done is place my custom component inside the pdb module under > modules > pdb_ng2 > components > my_component. 

Everything is working fine, I can see my block on the page. However, when I upgrade the pdb module my component will be lost. 

So, is the correct procedure for upgrades to store my custom component on github/bitbucket/my desktop whatever, upgrade the module and then re-place the component in the pdb module? 

Or am I just completely wrong and we're supposed to be building our custom components in our own custom module?

**Comment by mrconnerton** [comment]
Doing what you are doing, I would say you would upgrade kinda like you would upgrade drupal core. Copy your components out, upgrade the module, copy them back in.

However with that said there are better places to put your components so you won't have that issue. Since pdb is using the core discovery api to find them, in theory you can place them anywhere drupal looks for modules, themes, etc.

We are at Drupal Camp Asheville sprinting on the module now. I'm going to do some experiments on different places you can put your components and will make some documentation and link back here.

**Comment by mrconnerton** [comment]
So after some research the fastest way to start adding components is to create a
`<docroot>/modules/components folder`. So yours could live in `<docroot>/modules/components/ng2/my_component`

The components folder doesn't actually need to be a Drupal module, it just has to be in the "modules", "profile", or "themes" folder to get detected.

**Comment by mrconnerton** [comment]
I have created an issue and patch at https://www.drupal.org/node/2783389 which will allow you to setup non-standard directories in the root that get included in the scan.

**Comment by acha5066** [comment]
Awesome. Thanks very much for your help.
