### ISSUE TITLE
pdb_ng2 - put components inside the custom/theme directory

### ISSUE THREAD

**Issue by Dralac** [mrjmd/pdb#95]
Is there any progress on custom components location, per this pull request comment? https://github.com/mrjmd/pdb/pull/92#issuecomment-256744796

I'm currently limited to put components to pdb module directory, but I really want them separate and used them from my custom module or theme directory. 

I managed that by overriding systemConfig.js and adding my own path to `map`  and `packages` variables, but I'd really like to know if there is any other way I can achieve this currently?

**Comment by mrjmd** [comment]
This should be working for most components in the latest 8.x-1.x branch now without needing to add anything to systemConfig. I have tested putting component directories into sites/all/modules/ng2_components and it's working fine without any additions to systemConfig.

Also, for cases where it may still be necessary, the latest 8.x-1.x branch now provides the ability to add to `map` and `packages` via your info.yml file instead of editing `systemConfig.js` directly, for an example of this see: `pdb/modules/pdb_ng2/components/ng2_charts/ng2_pie_chart/ng2_pie_chart.info.yml`.

**Comment by Dralac** [comment]
Thanks @mrjmd, all good now
